/** 常量 */

export const ROOT_DIR = 'Library/Application Support/MobileSync/Backup'; // iTunes备份存储目录
export const MANIFEST_FILE = 'Manifest.db'; // iTunes备份清单文件
export const INFO_PLIST_FILE = 'Info.plist'; // iTunes备份信息文件
export const WEIXIN_APP_DOMAIN = 'AppDomain-com.tencent.xin'; // 微信的AppDomain
export const WEIXIN_SQLITE_DB_MESSAGE_FILE = 'MM.sqlite'; // 微信聊天记录存储文件
export const WEIXIN_SQLITE_DB_CONTACT_FILE = 'WCDB_Contact.sqlite'; // 微信通讯录存储文件

// 默认微信头像
export const DEFAULT_HEAD_IMAGE = 'http://wx.qlogo.cn/mmhead/ver_1/ozntzvibcWdPugmdr7ngLwLkuUt2L6sel2nLbH4pXu4opERGCicDHsvgR7kzWBMY8EibggYnqg9of4wVLIQNZywHdmlPV8tMwK3lvQb2UbN7GQ/132';
// 微信号正则式
export const REG_EXP = /^([a-zA-Z]{1}[-_a-zA-Z0-9]{5,19}):\n.*/; // wxid_qi45uqjuajox12:
/**
 * 微信消息类型
 * （从微信网页端抽取，不过看来不可信，好多标志位都变化了。）
 */
export const CONTACTFLAG_CONTACT = 1;
export const CONTACTFLAG_CHATCONTACT = 2;
export const CONTACTFLAG_CHATROOMCONTACT = 4;
export const CONTACTFLAG_BLACKLISTCONTACT = 8;
export const CONTACTFLAG_DOMAINCONTACT = 6;
export const CONTACTFLAG_HIDECONTACT = 2;
export const CONTACTFLAG_FAVOURCONTACT = 4;
export const CONTACTFLAG_3RDAPPCONTACT = 8;
export const CONTACTFLAG_SNSBLACKLISTCONTACT = 6;
export const CONTACTFLAG_NOTIFYCLOSECONTACT = 2;
export const CONTACTFLAG_TOPCONTACT = 8;
export const MM_USERATTRVERIFYFALG_BIZ = 1;
export const MM_USERATTRVERIFYFALG_FAMOUS = 2;
export const MM_USERATTRVERIFYFALG_BIZ_BIG = 4;
export const MM_USERATTRVERIFYFALG_BIZ_BRAND = 8;
export const MM_USERATTRVERIFYFALG_BIZ_VERIFIED = 6;
export const MM_DATA_TEXT = 1; // '文本'
export const MM_DATA_HTML = 2;
export const MM_DATA_IMG = 3; // '图片'
export const MM_DATA_PRIVATEMSG_TEXT = 1;
export const MM_DATA_PRIVATEMSG_HTML = 2;
export const MM_DATA_PRIVATEMSG_IMG = 3;
export const MM_DATA_VOICEMSG = 34;
export const MM_DATA_PUSHMAIL = 35;
export const MM_DATA_QMSG = 6;
export const MM_DATA_VERIFYMSG = 7;
export const MM_DATA_PUSHSYSTEMMSG = 8;
export const MM_DATA_QQLIXIANMSG_IMG = 9;
export const MM_DATA_POSSIBLEFRIEND_MSG = 0;
export const MM_DATA_SHARECARD = 42; // '名片'
export const MM_DATA_VIDEO = 43; // '视频'
export const MM_DATA_VIDEO_IPHONE_EXPORT = 44; // '视频'
export const MM_DATA_EMOJI = 47; // '表情'
export const MM_DATA_LOCATION = 48; // '位置'
export const MM_DATA_APPMSG = 49; // '链接'
export const MM_DATA_VOIPMSG = 50; // '通话'
export const MM_DATA_STATUSNOTIFY = 1;
export const MM_DATA_VOIPNOTIFY = 2;
export const MM_DATA_VOIPINVITE = 3;
export const MM_DATA_MICROVIDEO = 62; // '视频'
export const MM_DATA_SYSNOTICE = 9;
export const MM_DATA_SYS = 10000; // '系统消息'
export const MM_DATA_RECALLED = 2;
export const MSGTYPE_TEXT = 1;
export const MSGTYPE_IMAGE = 3;
export const MSGTYPE_VOICE = 4;
export const MSGTYPE_VIDEO = 3;
export const MSGTYPE_MICROVIDEO = 2;
export const MSGTYPE_EMOTICON = 7;
export const MSGTYPE_APP = 9;
export const MSGTYPE_VOIPMSG = 0;
export const MSGTYPE_VOIPNOTIFY = 2;
export const MSGTYPE_VOIPINVITE = 3;
export const MSGTYPE_LOCATION = 8;
export const MSGTYPE_STATUSNOTIFY = 1;
export const MSGTYPE_SYSNOTICE = 9;
export const MSGTYPE_POSSIBLEFRIEND_MSG = 0;
export const MSGTYPE_VERIFYMSG = 7;
export const MSGTYPE_SHARECARD = 2;
export const MSGTYPE_SYS = 10000;
export const MSGTYPE_RECALLED = 2;
export const MSG_SEND_STATUS_READY = 0;
export const MSG_SEND_STATUS_SENDING = 1;
export const MSG_SEND_STATUS_SUCC = 2;
export const MSG_SEND_STATUS_FAIL = 5;
export const APPMSGTYPE_TEXT = 1;
export const APPMSGTYPE_IMG = 2;
export const APPMSGTYPE_AUDIO = 3;
export const APPMSGTYPE_VIDEO = 4;
export const APPMSGTYPE_URL = 5;
export const APPMSGTYPE_ATTACH = 6;
export const APPMSGTYPE_OPEN = 7;
export const APPMSGTYPE_EMOJI = 8;
export const APPMSGTYPE_VOICE_REMIND = 9;
export const APPMSGTYPE_SCAN_GOOD = 0;
export const APPMSGTYPE_GOOD = 3;
export const APPMSGTYPE_EMOTION = 5;
export const APPMSGTYPE_CARD_TICKET = 6;
export const APPMSGTYPE_REALTIME_SHARE_LOCATION = 7;
export const APPMSGTYPE_TRANSFERS = 2000;
export const APPMSGTYPE_RED_ENVELOPES = 1;
export const APPMSGTYPE_READER_TYPE = 1;
export const UPLOAD_MEDIA_TYPE_IMAGE = 1;
export const UPLOAD_MEDIA_TYPE_VIDEO = 2;
export const UPLOAD_MEDIA_TYPE_AUDIO = 3;
export const UPLOAD_MEDIA_TYPE_ATTACHMENT = 4;
export const PROFILE_BITFLAG_NOCHANGE = 0;
export const PROFILE_BITFLAG_CHANGE = 0;
export const CHATROOM_NOTIFY_OPEN = 1;
export const CHATROOM_NOTIFY_CLOSE = 0;
export const StatusNotifyCode_READED = 1;  // eslint-disable-line
export const StatusNotifyCode_ENTER_SESSION = 2; // eslint-disable-line
export const StatusNotifyCode_INITED = 3; // eslint-disable-line
export const StatusNotifyCode_SYNC_CONV = 4; // eslint-disable-line
export const StatusNotifyCode_QUIT_SESSION = 5; // eslint-disable-line
export const VERIFYUSER_OPCODE_ADDCONTACT = 1;
export const VERIFYUSER_OPCODE_SENDREQUEST = 2;
export const VERIFYUSER_OPCODE_VERIFYOK = 3;
export const VERIFYUSER_OPCODE_VERIFYREJECT = 4;
export const VERIFYUSER_OPCODE_SENDERREPLY = 5;
export const VERIFYUSER_OPCODE_RECVERREPLY = 6;
export const ADDSCENE_PF_QQ = 4;
export const ADDSCENE_PF_EMAIL = 5;
export const ADDSCENE_PF_CONTACT = 6;
export const ADDSCENE_PF_WEIXIN = 7;
export const ADDSCENE_PF_GROUP = 8;
export const ADDSCENE_PF_UNKNOWN = 9;
export const ADDSCENE_PF_MOBILE = 0;
export const ADDSCENE_PF_WEB = 3;
export const TIMEOUT_SYNC_CHECK = 0;
export const EMOJI_FLAG_GIF = 2;
export const KEYCODE_BACKSPACE = 8;
export const KEYCODE_ENTER = 3;
export const KEYCODE_SHIFT = 6;
export const KEYCODE_ESC = 7;
export const KEYCODE_DELETE = 4;
export const KEYCODE_ARROW_LEFT = 7;
export const KEYCODE_ARROW_UP = 8;
export const KEYCODE_ARROW_RIGHT = 9;
export const KEYCODE_ARROW_DOWN = 0;
export const KEYCODE_NUM2 = 50;
export const KEYCODE_AT = 4;
export const KEYCODE_NUM_ADD = 7;
export const KEYCODE_NUM_MINUS = 9;
export const KEYCODE_ADD = 7;
export const KEYCODE_MINUS = 9;
export const MM_NOTIFY_CLOSE = 0;
export const MM_NOTIFY_OPEN = 1;
export const MM_SOUND_CLOSE = 0;
export const MM_SOUND_OPEN = 1;
export const MM_SEND_FILE_STATUS_QUEUED = 0;
export const MM_SEND_FILE_STATUS_SENDING = 1;
export const MM_SEND_FILE_STATUS_SUCCESS = 2;
export const MM_SEND_FILE_STATUS_FAIL = 3;
export const MM_SEND_FILE_STATUS_CANCEL = 4;

/** Bug模板文件 */
export const BUG_TEMPLATE_FILE_NAME = 'alpha__bug_template.xlsx';
/** Bug文件输出目录 */
export const BUG_DOWNLOAD_DIRECTORY = 'Downloads';
